version: 2

sources:
  - name: bronze
    database: lake
    schema: bronze
    tables:
      - name: players_profiles
        meta:
          dagster:
            asset_key: ["bronze__players_profiles"]
      - name: players_games
        meta:
          dagster:
            asset_key: ["bronze__players_games"]
  - name: silver
    database: lake
    schema: silver
    tables:
      - name: players_profiles
      - name: players_games
  - name: gold
    database: lake
    schema: gold
    tables:
      - name: dim__players
      - name: fact__games
