version: 2

sources:
  - name: raw
    database: lake
    schema: raw
    tables:
      - name: players_profiles
        meta:
          dagster:
            asset_key: ["raw__players_profiles"]
      - name: players_games
        meta:
          dagster:
            asset_key: ["raw__players_games"]
