version: 2

sources:
  - name: bronze
    database: lake
    schema: bronze
    tables:
      - name: players_profiles
        meta:
          dagster:
            asset_key: ["bronze__players_profiles"]
      - name: players_games
        meta:
          dagster:
            asset_key: ["bronze__players_games"]
